pkg/gomega/assertions/eventually_configmap.go

Removes the statement mentioning polling until success as its not implemented by the assertion.

Modify gomega configmap assertion docstring

---

go.mod
pkg/clients/openshift/client.go

allows a client to impersonate another user/serviceaccount to test
permissions

pkg/clients/openshift: implement impersonation

---

pkg/openshift/rosa/cluster.go

This PR ports the additional ROSA create cluster options that the existing ROSA provider supports within osde2e.
- [SDCICD-1043](https://issues.redhat.com/browse/SDCICD-1043)

SDCICD-1043: Port missing ROSA create cluster options from osde2e

---

pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/regions.go

Region check will tell the caller function that the region they supplied either does not support hosted control plane clusters or multi az clusters. Providing the caller function with information up front over performing additional steps prior to initiating cluster creation.

ROSA provider: perform a region check prior to cluster creation

---

pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/versions.go

This PR adds a new method named `Versions` that can be called to return back a list of available versions to deploy clusters with based on the provided options (channel group and hosted control plane support).

ROSA provider: support getting versions

---

pkg/clouds/aws/credentials.go
pkg/openshift/rosa/regions.go
pkg/openshift/rosa/rosa.go

When a rosa provider object is constructed, if the region is an empty string or random is provided. A random region will be automatically assigned.

ROSA provider: add support for randomly selecting AWS region to use

---

pkg/openshift/rosa/cluster.go

Previously when deleting a cluster and hosted control plane is enabled. It will always try to delete the aws vpc that was created. Since the create cluster allows the caller to supply subnet ids (by passing creating a vpc), we need to be able to skip deleting vpc when subnet ids are passed.
This commit introduces a new field to the delete cluster options struct. Allowing the caller to turn off vpc deletion. Caller will know if they provided subnet ids or had the vpc be created. Leaving the core method to act on the input.

ROSA provider: add a field to turn on/off vpc deletion

---

pkg/clients/openshift/healthcheck.go
pkg/openshift/rosa/cluster.go

This PR updates the ROSA hosted control plane cluster health checks to verify the number of compute nodes the cluster returns matches what is defined when the cluster was created.

ROSA provider: update HCP cluster health check to verify compute node count

---

pkg/openshift/rosa/cluster.go

The wait for cluster to be healthy method previously was passing in the cluster id to find the cluster in ocm. The find cluster method actually requires the cluster name. This PR passes in the cluster name over cluster id.

ROSA provider: pass in cluster name to waitForClusterToBeHealthy over cluster ID

---

pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/oidcconfig.go
pkg/openshift/rosa/operatorroles.go

This commit adjusts the ROSA delete cluster method to properly clean up a clusters operator roles and oidc provider. Resources were being left over due to there are different options that need to be provided when you use an oidc config id.
Reference: https://github.com/openshift/rosa/blob/master/cmd/dlt/cluster/cmd.go#L114-L124

ROSA provider: adjust clean up operations based on cluster settings

---

examples/rosadeletecluster/rosadeletecluster.go
pkg/clients/ocm/credentials.go
pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/rosa.go

This PR aims to address minor tweaks to the ROSA provider to make it even more consumable to other go modules (e.g. osde2e) based on their needs. The changes made in this PR, does not impact the end result of the provider (to create a cluster or delete a cluster).
Changes included in this PR:
- Fix a bug found when logging the ROSA CLI command to run with its options
- Accept a new parameter to define where a clusters kubeconfig file should be written to
- Remove setting defaults for VPC/OIDC config deletion
- Set the minimum ROSA version to 1.2.23
- Set where ROSA login writes the `ocm.json` file to (defaults it to systems temporary directory)
- Remove setting subnet ids option twice
- Add a new create cluster options field to use the default account roles prefix (ManagedOpenShift) if …

SDCICD-1049: ROSA Provider Updates

---

pkg/openshift/rosa/rosa.go

This PR includes the following changes to the provider:
- When a new ROSA provider is constructed, when checking the ROSA version meets the minimum version defined, it will log this. Providing a way for the caller program to know what exact version of ROSA was used.
- Add a new `Uninstall` method that takes care of removing the ROSA binary that may have been downloaded at runtime to the file systems temporary directory. It will not remove the ROSA binary if one was found (it was never downloaded to begin).

ROSA Provider: Miscellaneous Updates From Continued Testing

---

pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/gologrkeys.go

This PR updates the logging messages for the ROSA provider to include the timeout duration to wait for a cluster to be installed.

ROSA provider: log the timeout to wait for a cluster to be installed

---

pkg/openshift/rosa/cluster.go

this error was being dropped without being logged or wrapped and
returned

pkg/openshift/rosa: wrap wait for cluster install err

---

examples/rosadeletecluster/rosadeletecluster.go
pkg/openshift/rosa/cluster.go

This PR allows the ROSA `DeleteCluster` method to accept either the cluster name or id to be deleted. Previously it was looking for the cluster name.

pkg/openshift/rosa: accept either cluster name or id when deleting

---

pkg/openshift/rosa/cluster.go

More recently we have been seeing the health check timeouts failing "waiting for nodes to be ready". This commit will double the timeout to 20 minutes from 10 and can be re-tuned once we get a better new average of how long it takes.

pkg/openshift/rosa: increase hcp health check timeout to 20 minutes

---

pkg/clients/openshift/healthcheck.go

- pkg/clients/openshift: double timeout for healthcheck job to appear

increase cluster ready job wait timeout

---

pkg/openshift/rosa/rosa.go

Previously the rosa tar file was being downloaded to the file path where the go file is run. This fails when running within a prow CI job. To workaround this, we can download the tar file to the tmp directory of the container. Similar to where the actual rosa binary cli gets installed to.
PR aims to resolve the error seen [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.12-rosa-hcp/1691862241223118848).
```
2023/08/16 17:22:48 e2e.go:293: OSDE2E failed: could not setup cluster provider: failed to construct rosa provider: failed to create rosa.tar.gz tar file: open rosa.tar.gz: permission denied
```

pkg/openshift/rosa: download rosa tar file to tmp directory

---

pkg/clients/openshift/upgrade_operator.go

the pods are getting left up otherwise:
```
"level"=0 "msg"="child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning"
```

pkg/clients/openshift: set delete propagation for deleting query pod

---

pkg/openshift/rosa/accountroles.go
pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/rosa.go

Ref Thread:
https://redhat-internal.slack.com/archives/CMK13BP4J/p1692724384885839
https://issues.redhat.com/browse/SDCICD-1086
The purpose of this PR is to update the provider logic for the Rosa provider to match the new behavior found in Rosa 1.2.26+
1. The command: 'rosa create account-roles --mode auto' now creates the HCP account roles as well which ups the roles created to 7 instead of 4. 
2. It seems they are handling oidcconfigids a bit different as well. When trying to run the 'rosa create cluster ...options' without the '--oidc-config-id $id' the binary exits with an os.Exit(1). This seems like a bug as the log reads 'WARN: No OIDC Configuration found; will continue with the classic flow.' So to get by I'm swapping the oidcconfigid creation to happen for STS clusters as well. …

Updates based on Rosa 1.2.26-rc1

---

pkg/openshift/rosa/cluster.go

[SDCICD-1086](https://issues.redhat.com/browse/SDCICD-1086)
This enables Rosa non sts cluster testing. The current iteration requires the AWS Credentials to use the osdCCSAdmin account.

Add support for Rosa non sts

---

go.mod
go.sum
pkg/openshift/rosa/rosa.go

a nightly job failed to clean up due to i/o timeout when downloading the CLI. Set up retries so we don't fail for a network blip.
go-retryablehttp doesn't retry timeout errors by default, so configure a custom retry to check for the expected error.
https://stackoverflow.com/a/68636675
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts/1701824344436510720
```
could not setup cluster provider: failed to construct rosa provider: failed to download https://mirror.openshift.com/pub/openshift-v4/clients/rosa/1.2.25/rosa-linux.tar.gz: Get "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/1.2.25/rosa-linux.tar.gz": dial tcp 13.35.116.126:443: i/o timeout        
```

pkg/openshift/rosa: retry rosa cli download

---

pkg/clients/openshift/healthcheck.go
pkg/openshift/rosa/cluster.go

round the value to seconds and format it so it is printed in a human-readable way

misc: format timeout in log messages

---

pkg/clients/openshift/client.go

allow creating a new openshift client from just the base restconfig object
see https://github.com/openshift/osde2e/pull/2151

clients/openshift: NewFromRestConfig

---

pkg/clients/openshift/errors.go
pkg/clients/openshift/healthcheck.go

the check fails randomly due to server errors which can be handled and retried. retryable function is ripped from ceph-csi e2e tests https://github.com/red-hat-storage/ceph-csi/blob/cf3f32f9996dc38671062ea0e36fae66f28dadb5/e2e/errors.go#L26

clients/openshift: handle healthcheck server errors

---

pkg/clients/openshift/errors.go

healthceck polling is failing locally for `http2: client connection lost` often. Add it to the list to retry
```
E1019 04:20:17.294344   24959 healthcheck.go:40]  "msg"="failed waiting for healthcheck job to finish" "error"="Get \"https://api.osde2e-sints.928m.s1.devshift.org:6443/apis/batch/v1/namespaces/openshift-monitoring/jobs/osd-cluster-ready\": http2: client connection lost"
```
https://github.com/openshift/kubernetes/blob/c0449761f4ad0c3a585990c26aea90a1dadb82cb/staging/src/k8s.io/apimachinery/pkg/util/net/util.go#L51C1-L54

clients/openshift: handle IsHttp2ConnectionLost error

---

pkg/openshift/rosa/rosa.go

Ref Error: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45379/rehearse-45379-pull-ci-openshift-osde2e-main-hypershift-pr-check/1721835111948750848
```
2023/11/07 10:26:08 events.go:27: Fail event: InstallFailed
2023/11/07 10:26:08 e2e.go:87: Failed to set up or retrieve cluster: could not launch cluster: create cluster failed: error: failed to wait for command to finish: exit status 1, stderr: ERR: Failed to create cluster: Creating hosted control plane cluster requires ROSA 1.2.29 or higher. Go to https://console.redhat.com/openshift/downloads#tool-rosa to download the latest version.
```

Bump minimumVersion for Rosa CLI to 1.2.29

---

pkg/openshift/rosa/rosa.go

failing to create hcp clusters with current version, bump to latest
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45379/rehearse-45379-pull-ci-openshift-osde2e-main-hypershift-pr-check/1724789996373676032

openshift/rosa: bump min version to 1.2.30

---

pkg/gomega/matchers/contain_item_with_prefix.go
pkg/gomega/matchers/contain_item_with_prefix_test.go

Starting 4.15, "name" value on clusterrole, clusterrolebinding objects for an operator are getting truncated to fit olm requirements
These objects contain a label "olm.owner" if they belong to the same operator which isn't truncated.
Adding a matcher to use for these assertions on operator tests.

matcher for olm.owner label

---

pkg/openshift/rosa/cluster.go

Using the incorrect roles is causing issues in CI https://github.com/openshift/release/pull/47894
[OSD-20366](https://issues.redhat.com//browse/OSD-20366)

Correctly use HCP account roles when creating HCP clusters

---

pkg/openshift/rosa/rosa.go

rosa version now includes some junk related to the build that is not
semver compatible. Just return the full thing since we no longer gate
logic based on the version.
```
❯ ./rosa version
1.2.35 (Build: )
I: Your ROSA CLI is up to date.
```
https://redhat-internal.slack.com/archives/CMK13BP4J/p1708967421818679

pkg/openshift/rosa: stop parsing version

---

go.mod
pkg/openshift/rosa/cluster.go

the value of ExpirationDuration should be respected directly and not
mutated to produce a higher value
`opts.ExpirationDuration = 8 * time.Hour`

pkg/openshift/rosa: use provided duration directly

---

.ci-operator.yaml

this allows for easier bumping of go versions within the repo

misc: add .ci-operator.yml config

---

pkg/openshift/rosa/cluster.go

Fixing `--additional-trust-bundle-file` flag for `rosa create cluster` command for byo-vpc-proxy-install setup. 
Error:
```shell
Failed to execute root command: bad flag syntax: ----additional-trust-bundle-file
```
Reference job - https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-osde2e-main-rosa-stage-e2e-byo-vpc-proxy-install/1795530782698115072

Fixing additional-trust-bundle-file flag usage

---

.github/dependabot.yml

group them together so they stay in sync and can be bumped easier

misc: group k8s dependabot bumps

---

pkg/openshift/rosa/rosa.go

Have to remove this whoami check. 
When I tested locally I didn't realize that I already have an OCM session locally. 
This flow breaks on a fresh session. 
ERR: Failed to create OCM connection: either a token, an user name and password or a client identifier and secret are necessary, but none has been provided

Remove whoami check from verifylogin

---

pkg/openshift/rosa/cluster.go

Expiration feature is unsupported in prod and we get errors if we try to set it.
Jobs running in prod fail due to returned errors.
Self service jobs are open to prod runs. It's also a good idea prevent failures for any future prod jobs.

SDCICD-1252 remove expiration date setting from prod clusters

---

pkg/clients/openshift/metadata.go

create metadata with few initial getters for
- STS
- CCS
- Cloud provider
- Region
Gets  osd-cluster-metadata configmap from "openshift-config" namespace to return these values
Brought up during [SDCICD-885](https://issues.redhat.com//browse/SDCICD-885) (CIO harness uses numerous of these configs)

create metadata helper for openshift client

---

pkg/openshift/rosa/cluster.go

the SDN migration effort needs additional flags for cluster provisioning:
```
--enable-autoscaling
--min-replicas
--max-replicas
--etcd-encryption
```
when min/max-replicas is set, replicas cannot be
output:
```
"level"=0 "msg"="Command" "rosa_command"="rosa create cluster --output json --cluster-name creed-sdn-ovn-1 --channel-group stable --compute-machine-type m5.xlarge --machine-cidr 10.0.0.0/16 --region us-east-1 --version 4.14.14 --host-prefix 0 --oidc-config-id 2crf9hdst7t9vt9n7rpbvtremfai722s --yes --role-arn arn:aws:iam::3696:role/ManagedOpenShift-4.14-Installer-Role --controlplane-iam-role arn:aws:iam::696:role/ManagedOpenShift-4.14-ControlPlane-Role --support-role-arn arn:aws:iam::3696:role/ManagedOpenShift-4.14-Support-Role --worker-iam-role …
```

openshift/rosa: support additional parameters

---

pkg/openshift/rosa/cluster.go

the SDN migration effort needs an additional flag for cluster provisioning:
`--no-proxy`

support no-poxy paramater

---

.ci-operator.yaml
go.mod

go 1.21 went EOL last month, deps are now requiring 1.22

go.mod: bump to go 1.22

---

examples/rosadeletecluster/rosadeletecluster.go
pkg/openshift/rosa/cluster.go

Forgot to make changes to the delete functions to enable this for PrivateLink as well.

Enables the PrivateLink Cluster VPC deletion

---

pkg/clients/openshift/healthcheck.go
pkg/openshift/osd/cluster.go
pkg/openshift/rosa/cluster.go

/hold
implement the initial OSD cluster provisioning based on what exists
today in osde2e. Next would be to adapt osde2e to use this provider
similar to what was done with the rosa provider. Everything needed
should be provided to the lower level API and get a clusterID back.
```go
provider, err := osd.New(ctx, os.Getenv("OCM_TOKEN"), ocm.Integration, textlogger.NewLogger(textlogger.NewConfig()))
if err != nil {
panic(err)
}
opts := &osd.CreateClusterOptions{
CCS:              true,
ClusterName:      clusterName,
CloudProvider:    osd.CloudProviderAWS,
ComputeNodeCount: 2,
ChannelGroup:     "nightly",
Version:          "openshift-v4.16.0-0.nightly-2024-06-13-213831-nightly",
Region:           "us-east-1",
CreateAWSClusterOptions: &osd.CreateAWSClusterOptions{
AccountID: …
```

osd: cluster provisioning

---

pkg/openshift/rosa/cluster.go

A vpc is created for hosted planes in each cluster creation by default. Therefore they should be set to be deleted at the end.

Set default for DeleteHostedCPVPC for hosted plane.

---

pkg/clients/ocm/client.go
pkg/openshift/rosa/rosa.go

This update enables the client and clientsecrets to be used for login in commercial and not just fedramp.

SDCICD-1351 Update the client logins to use client credentials.

---

pkg/openshift/rosa/rosa.go

https://github.com/openshift-online/ocm-cli?tab=readme-ov-file#multiple-concurrent-logins-with-ocm_config
https://issues.redhat.com/browse/SDE-4270
This PR fixes an issue I encountered when introducing log in through the client credentials. The env var OCM_CONFIG is used from the OCM cli to store login information and needs to be set to the os.TempDir() which will allow the OSDe2e docker image all required permissions in the local file system.

Update the OCM_CONFIG variable to work with client credentials.

---

pkg/openshift/rosa/cluster.go

We came across panic. It seems that `response.Total()==1` check is not sufficient to ensure response items are not empty. 
`panic({0x33ce740?, 0xc00129e000?})
/usr/lib/golang/src/runtime/panic.go:785 +0x132
github.com/openshift/osde2e-common/pkg/openshift/rosa.(*Provider).findCluster(0xc000ebec60, {0x3ce84e8, 0xc00126c070}, {0xc001043c04, 0xc})
/go/pkg/mod/github.com/openshift/osde2e-common@v0.0.0-20250425180409-b9162e21257f/pkg/openshift/rosa/cluster.go:512 +0x425`

Fix: add exception for nil pointer panic

---

internal/cmd/cmd.go
pkg/openshift/rosa/cluster.go
pkg/openshift/rosa/rosa.go

```
commit 6b62b290b04870da04c69e4bbf8d3f76304ef748
Author: Brady Pratt <bpratt@redhat.com>
Date:   Thu Jul 10 06:53:17 2025 -0500
pkg/openshift/rosa: run rosa whoami on creation
fetch the contents of `rosa whoami` on new provider so we have access to
things like account id and default region (unused).
We can then set the `BillingAccountID` to the account we are running
under
commit 0d27e13bb6f03776583dae7419cc1c94a5782bba
Author: Brady Pratt <bpratt@redhat.com>
Date:   Thu Jul 10 02:02:31 2025 -0500
internal/cmd: return bytes.Buffer
return a struct and not an interface following the Go idiom of `Accept
interfaces, return structs`. This allows us to operate on the type
directly as what it is and will always be (a bytes.Buffer)
Signed-off-by: …
```

pkg/openshift/rosa: default BillingAccountID
