README.md
This PR initializes the projects readme.
=> Initialize projects readme

pkg/gomega/assertions/eventually_configmap.go
Added configmap assertion based on eventuallyDeployment assertion
Used in Splunk forwarder operator test.
=> assertion for Config map exists

pkg/openshift/rosa/cluster.go
By default cluster health checks will be performed once the cluster is in a ready state. If the caller would like to skip health checks, they can do this by simply setting the field in the create cluster options struct when calling `createCluster`.
=> ROSA provider: add option to skip health checks

pkg/openshift/rosa/regions.go
This PR is a follow up to #16 to use the custom region error. Along with it, since additional methods now exist for regions. It modifies the custom region error to accept the action being performed. Whereas previously it was specific to region check.
=> ROSA provider: modify regions custom error to support different actions

pkg/openshift/rosa/cluster.go
By default if the caller provides no oidc config id, it will be created and deleted. Some programs calling create/delete cluster methods, may want to provide their own oidc config id to create the cluster. In those cases, it may not want to be deleted afterwards "static oidc config". This commit introduces a new field that the caller can set to disable create/delete of the oidc config for the cluster.
=> ROSA provider: add a field to turn on/off oidc config create/delete

pkg/clients/openshift/healthcheck.go, pkg/openshift/osd/gologrkeys.go, pkg/openshift/osd/upgrade.go
This PR modifies the go logger keys from initial camel case format to snake case.
=> Switch Go Logger Keys From CamelCase to SnakeCase

go.mod, go.sum, pkg/clients/openshift/healthcheck.go, pkg/openshift/osd/upgrade.go, pkg/openshift/rosa/cluster.go, pkg/openshift/rosa/gologrkeys.go, pkg/openshift/rosa/regions.go, pkg/openshift/rosa/rosa.go, pkg/openshift/rosa/versions.go
- pkg/clients/openshift/healthcheck: wait for job to exist
- pkg/clients/openshift/healthcheck: wrap errors
- pkg/openshift/rosa: poll until nightly version is found
=> pkg/openshift: poll for additional things

pkg/clients/openshift/healthcheck.go
=> pkg/clients/openshift: wrap healthcheck failure err

pkg/openshift/rosa/cluster.go
Previously you were able to provide a working directory field when creating/deleting clusters. This allowed the provider to write various files (e.g. aws vpc terraform files, cluster install/uninstall logs) to disk for later consumption
There may be certain files the provider may not wish to be archived and just temporarily written to disk. This commit introduces a new field to create/delete clusters options `ArtifactDir`. This directory is where artifacts can be written/saved off for later usage. While the `WorkingDir` is meant to be a temporary location and files are not archived. With this change `WorkingDir` will write files such as terraform files and `ArtifactDir` will store files such as install/uninstall logs. When this field is not provided, it defaults to the file systems …
=> pkg/openshift/rosa: new artifact directory field for create/delete clusters

pkg/clients/openshift/healthcheck.go
=> pkg/clients/openshift: wrap healthcheck failure error

pkg/clients/openshift/client.go, pkg/clients/openshift/healthcheck.go
both fetch the logs of the default or first container found
=> pkg/clients/openshift: implement GetPodLogs and GetJobLogs

pkg/clients/openshift/upgrade_operator.go
port over functionality to upgrade an operator from n-1 version
=> clients/openshift: operator upgrade

OWNERS
This PR removes `ryankwilliams` from the approvers/reviewers.
=> Modify OWNERS File

OWNERS
Onboarding Yiqin to Cicada as code reviewer
[SDCICD-1090](https://issues.redhat.com//browse/SDCICD-1090)
=> adding yiqin to reviewers

pkg/openshift/rosa/rosa.go
it is causing unnecessary churn and jobs to be broken, lets rely on the
version check that rosa CLI does on its own to ensure we are running at
least the minimum version.
https://issues.redhat.com/browse/SDCICD-1185
=> SDCICD-1185: remove rosa version check

pkg/clients/openshift/client.go
moving  watchjob function  from osde2e to common
=> add watchJob function

pkg/clients/openshift/client.go
=> clients/openshift: get job directly

.github/dependabot.yml
this is copied from osde2e but set to daily
=> misc: add dependabot config

pkg/openshift/rosa/cluster.go
Simple flag enablement for non-sts clusters based on this request from James. 
https://redhat-internal.slack.com/archives/CMK13BP4J/p1717698164120189
=> enable rosa non-sts or mint-mode for osde2e clusters

pkg/clients/openshift/upgrade_operator.go
address todo item to show job logs when CSV getter job fails
=> address todo item to show job logs when CSV getter job fails

pkg/openshift/rosa/cluster.go
Added a new flag to support billingAccount when creating the cluster for ROSA.
=> Added billing account flag to the create cluster for ROSA

pkg/clients/openshift/client.go
the format should be namespace/name
=> pkg/clients/openshift: fix namespace/name err msg

pkg/openshift/rosa/cluster.go
if we fail to create the cluster for any reason, delete the VPC that was created so we aren't leaving resources up
=> SDCICD-1600: clean up VPC on creation failure

pkg/openshift/rosa/cluster.go
if we fail to create any resource, follow up and delete the previously created resources.
In cases we would fail to create the VPC, the account roles and oidc-config are both left up after we exit. Track the creation of them and delete them on any following creation error.
1. Create account roles
2. Create oidc-config (if fails: delete account roles if custom)
3. Create VPC (if fails: delete oidc-config, account roles)
4. Create cluster (if fails: delete vpc, oidc-config, account roles)
closes [SDCICD-1603](https://issues.redhat.com//browse/SDCICD-1603)
example run
```
"level"=0 "msg"="OIDC config created!" "prefix"="osde2e-a51" "ocm_environment"="https://api.stage.openshift.com"
"level"=0 "msg"="Creating aws vpc" "cluster_name"="osde2e-a51" "aws_region"="us-west-2"
"level"=0 "msg"="AWS …
```
=> SDCICD-1603: pkg/openshift/rosa: cleanup resources on failure
